services:
  - type: web
    name: octagon
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: starter
    envVars:
      - key: APP_NAME
        value: Octagon
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_URL
        sync: false
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: pg-23532d33-cristoniaphilip-71d9.e.aivencloud.com
      - key: DB_PORT
        value: "12018"
      - key: DB_DATABASE
        value: octagon
      - key: DB_USERNAME
        value: avnadmin
      - key: DB_PASSWORD
        sync: false
      - key: DB_SSLMODE
        value: require
      - key: SESSION_DRIVER
        value: database
      - key: CACHE_STORE
        value: database
      - key: QUEUE_CONNECTION
        value: database
      - key: OPENAI_API_KEY
        sync: false
      - key: TICKETMASTER_API_KEY
        sync: false
      - key: META_ADS_ACCESS_TOKEN
        sync: false
      - key: GOOGLE_ADS_DEVELOPER_TOKEN
        sync: false
      - key: KLAVIYO_API_KEY
        sync: false
